name: Functional Test Pipeline

on:
  push:
    branches: 
      - master
  pull_request:

env:
  PROJECT_PATH: WTouch.Cli/WTouch.Cli.csproj
  EXE_PATH: ./WTouch.Cli/bin/Release/net6.0/ubuntu-x64/publish
  ARTIFACT_NAME: winTouch

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Ubuntu Project
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --framework net6.0 --runtime ubuntu-x64 --self-contained true /p:PublishSingleFile=true /p:DebugType=None

      - name: Renaming artifact
        run: mv ${{ env.EXE_PATH }}/touch ${{ env.EXE_PATH }}/winTouch

      - name: Uploading artifact
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: "${{ env.EXE_PATH }}/winTouch"
          if-no-files-found: error
          retention-days: 1
        
  test-file-creation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Making artifact executable
        run: chmod +x ./winTouch

      - name: Run touch command
        run: ./winTouch test_file.txt

      - name: Check file exists
        run: test -f test_file.txt

      - name: Where Am I? What is going on?
        run: ls -la
